export const SCHEMA_SQL = `
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS SportTemplate (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  CreatedAt TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS Category (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  SportTemplateId INTEGER NOT NULL REFERENCES SportTemplate(Id) ON DELETE CASCADE,
  Name TEXT NOT NULL,
  SortOrder INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Action (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  CategoryId INTEGER NOT NULL REFERENCES Category(Id) ON DELETE CASCADE,
  Name TEXT NOT NULL,
  HasOutcome INTEGER NOT NULL DEFAULT 1,
  SortOrder INTEGER NOT NULL DEFAULT 0,
  ColorClass TEXT
);

CREATE TABLE IF NOT EXISTS CommentTemplate (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  ActionId INTEGER NOT NULL REFERENCES Action(Id) ON DELETE CASCADE,
  Text TEXT NOT NULL,
  SortOrder INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Team (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  CreatedAt TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS Player (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  TeamId INTEGER NOT NULL REFERENCES Team(Id) ON DELETE CASCADE,
  Name TEXT NOT NULL,
  DefaultPosition TEXT,
  IsActive INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Squad (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  TeamId INTEGER NOT NULL REFERENCES Team(Id) ON DELETE CASCADE,
  Name TEXT NOT NULL,
  Tournament TEXT,
  Note TEXT,
  CreatedAt TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS SquadPlayer (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  SquadId INTEGER NOT NULL REFERENCES Squad(Id) ON DELETE CASCADE,
  PlayerId INTEGER NOT NULL REFERENCES Player(Id) ON DELETE CASCADE,
  Position TEXT,
  LineupRole TEXT NOT NULL DEFAULT 'starter' CHECK (LineupRole IN ('starter', 'substitute')),
  SortOrder INTEGER NOT NULL DEFAULT 0,
  UNIQUE (SquadId, PlayerId)
);

CREATE TABLE IF NOT EXISTS Match (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  SportTemplateId INTEGER NOT NULL REFERENCES SportTemplate(Id),
  HomeTeamId INTEGER NOT NULL REFERENCES Team(Id),
  AwayTeamId INTEGER NOT NULL REFERENCES Team(Id),
  MatchDate TEXT NOT NULL,
  Tournament TEXT,
  ScoreHome INTEGER,
  ScoreAway INTEGER,
  HomeSquadId INTEGER REFERENCES Squad(Id) ON DELETE SET NULL,
  AwaySquadId INTEGER REFERENCES Squad(Id) ON DELETE SET NULL,
  CreatedAt TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS MatchLineup (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  MatchId INTEGER NOT NULL REFERENCES Match(Id) ON DELETE CASCADE,
  TeamId INTEGER NOT NULL REFERENCES Team(Id),
  PlayerId INTEGER NOT NULL REFERENCES Player(Id),
  Position TEXT,
  LineupRole TEXT NOT NULL DEFAULT 'starter' CHECK (LineupRole IN ('starter', 'substitute')),
  SortOrder INTEGER NOT NULL DEFAULT 0,
  UNIQUE (MatchId, TeamId, PlayerId)
);

CREATE TABLE IF NOT EXISTS MatchPeriod (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  MatchId INTEGER NOT NULL REFERENCES Match(Id) ON DELETE CASCADE,
  PeriodNumber INTEGER NOT NULL,
  Label TEXT,
  UNIQUE (MatchId, PeriodNumber)
);

CREATE TABLE IF NOT EXISTS Event (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  MatchId INTEGER NOT NULL REFERENCES Match(Id) ON DELETE CASCADE,
  PeriodNumber INTEGER NOT NULL,
  TimestampSec INTEGER NOT NULL,
  SubjectType TEXT NOT NULL CHECK (SubjectType IN ('player', 'team')),
  PlayerId INTEGER REFERENCES Player(Id),
  TeamId INTEGER REFERENCES Team(Id),
  ActionId INTEGER REFERENCES Action(Id),
  Outcome TEXT CHECK (Outcome IN ('Success', 'Failure') OR Outcome IS NULL),
  Comment TEXT,
  CreatedAt TEXT NOT NULL DEFAULT (datetime('now')),
  CHECK (
    (SubjectType = 'player' AND TeamId IS NULL) OR
    (SubjectType = 'team' AND PlayerId IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS IX_Player_TeamId ON Player(TeamId);
CREATE INDEX IF NOT EXISTS IX_Squad_TeamId ON Squad(TeamId);
CREATE INDEX IF NOT EXISTS IX_SquadPlayer_SquadId ON SquadPlayer(SquadId);
CREATE INDEX IF NOT EXISTS IX_Match_HomeTeamId ON Match(HomeTeamId);
CREATE INDEX IF NOT EXISTS IX_Match_AwayTeamId ON Match(AwayTeamId);
CREATE INDEX IF NOT EXISTS IX_MatchLineup_MatchId ON MatchLineup(MatchId);
CREATE INDEX IF NOT EXISTS IX_Event_MatchId ON Event(MatchId);
`;
